# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='email address')),
                ('street', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('member_since', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'permissions': (('is_company', 'can create jobs offers'),),
            },
            bases=('users.entity',),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('short_name', models.CharField(max_length=30)),
            ],
            options={
                'permissions': (('is_school', 'represent the students'),),
            },
            bases=('users.entity',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'permissions': (('is_student', 'can apply to a job offer'),),
            },
            bases=('users.entity',),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JobPost'),
        ),
        migrations.AddField(
            model_name='student',
            name='prentending_jobs',
            field=models.ManyToManyField(blank=True, to='users.JobOffer'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_vinculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.School'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
        ),
    ]
