# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170224_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
